################################################################################
# Zabbix Compose
################################################################################
# docker compose -f docker-compose-3-Zabbix.yml up -d
################################################################################

services:

  zabbix-server:
    image: zabbix/zabbix-server-mysql:alpine-6.4-latest
    container_name: zabbix-server
    restart: unless-stopped
    environment:
      TZ: "Europe/Moscow"
      DB_SERVER_HOST: mysql-source
      MYSQL_DATABASE: zabbix
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: zabbixpass
      MYSQL_ROOT_PASSWORD: example
    networks:
      - default
    ports:
      - "10051:10051"

  zabbix-web:
    image: zabbix/zabbix-web-nginx-mysql:alpine-6.4-latest
    container_name: zabbix-web
    restart: unless-stopped
    environment:
      TZ: "Europe/Moscow"
      ZBX_SERVER_HOST: zabbix-server
      DB_SERVER_HOST: mysql-source
      MYSQL_DATABASE: zabbix
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: zabbixpass
      MYSQL_ROOT_PASSWORD: example
      PHP_TZ: "Europe/Moscow"
    networks:
      - default
    ports:
      - 8080:8080
    depends_on:
      - zabbix-server

  zabbix-agent:
    image: zabbix/zabbix-agent:latest
    container_name: zabbix-agent
    restart: unless-stopped
    init: true
    privileged: true
    environment:
      ZBX_HOSTNAME: zabbix-server
#      ZBX_SERVER_HOST: zabbix-server
      ZBX_PASSIVESERVERS: zabbix-server
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    networks:
      - default
    depends_on:
      - zabbix-server

networks:
  default:
    external: true
    name: otus-net
