################################################################################
# Nginx Compose
################################################################################
# docker compose -f docker-compose-Nginx.yml up -d
################################################################################

services:
  nginx:
    container_name: nginx
    image: nginx
    restart: always
    networks:
      - default
    ports:
      - "80:80"
    volumes:
      - /opt/otus-project/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - /opt/otus-project/nginx/log:/var/log/nginx/

networks:
  default:
    external: true
    name: otus-net
